
name: Deploy AMBA

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write

env:
  Location: "eastus"
  ManagementGroupPrefix: "4dc25713-7c26-4b9a-9cdf-bdb3522b2066"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: "Az CLI login"
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Az CLI Deploy AMBA ARM template
        id: deploy_amba
        shell: bash
        run: |
           az deployment mg create --template-file ./patterns/alz/alzArm.json --location "${{ env.Location }}" --management-group-id ${{ env.ManagementGroupPrefix }} --parameters ./patterns/alz/alzArm.param.json
